config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

Verboice::Application.routes.draw do

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :account

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show]

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      get :download
    end
  end

  resource :synthesizer do
    get :voices
  end

  resources :alerts do
    member do
      get :dismiss
    end
  end

  namespace :api do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end
    end
    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end
  end

  get 'permissions' => 'permissions#index'
  get 'permissions/autocomplete' => 'permissions#autocomplete'
  post 'permissions/add_account' => 'permissions#add_account'
  post 'permissions/update' => 'permissions#update'

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/models/channel.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class Channel < ActiveRecord::Base
  belongs_to :account
  belongs_to :call_flow
  has_one :project, :through => :call_flow

  has_many :call_logs, :dependent => :nullify
  has_many :queued_calls, :dependent => :destroy
  has_many :channel_permissions, :foreign_key => "model_id", :dependent => :destroy

  config_accessor :limit

  validates_presence_of :account

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :account_id
  validates_numericality_of :limit, :only_integer => true, :greater_than => 0, :if => :has_limit?

  after_commit :call_broker_create_channel, :on => :create
  after_commit :call_broker_update_channel, :on => :update
  after_commit :call_broker_destroy_channel, :on => :destroy

  serialize :config, Hash

  broker_cached

  def config
    self[:config] ||= {}
  end

  def self.inherited(child)
    # force all subclass to have :channel as model name
    child.instance_eval do
      def model_name
        Channel.model_name
      end
    end
    super
  end

  def call(address, options = {})
    queued_call = enqueue_call_to address, options
    call_log = queued_call.call_log

    begin
      if queued_call.not_before?
        BrokerClient.notify_call_queued id, queued_call.not_before
      else
        BrokerClient.notify_call_queued id
      end
    rescue Exception => ex
      call_log.warn "Unable to notify the broker about this new call. The call might be delayed"
    end

    call_log
  end

  def enqueue_call_to address, options
    via = options.fetch(:via, 'API')

    account = options[:account] || self.account

    if options[:call_flow_id]
      current_call_flow = account.find_call_flow_by_id(options[:call_flow_id])
    elsif options[:call_flow]
      current_call_flow = account.find_call_flow_by_name(options[:call_flow])
    elsif options[:flow]
      flow = options[:flow]
    elsif options[:callback_url]
      callback_url = options[:callback_url]
    else
      current_call_flow = call_flow
    end

    if current_call_flow
      project = current_call_flow.project
    elsif options[:project_id]
      project = account.find_project_by_id(options[:project_id])
    else
      project = self.project
    end

    schedule = options.has_key?(:schedule_id) ? project.schedules.find(options[:schedule_id]) : nil
    schedule ||= options.has_key?(:schedule) ? project.schedules.find_by_name!(options[:schedule]) : nil

    time_zone = nil
    not_before = nil
    if options[:not_before].nil? || options[:not_before].is_a?(String)
      time_zone = options[:time_zone].blank? ? ActiveSupport::TimeZone.new(project.time_zone || 'UTC') : (ActiveSupport::TimeZone.new(options[:time_zone]) or raise "Time zone #{options[:time_zone]} not supported")
      not_before = time_zone.parse(options[:not_before]) if options[:not_before].present?
    else
      not_before = options[:not_before]
    end

    session_id = options[:session_id]

    if session_id
      call_log = nil
    else
      call_log = call_logs.new(
        :account => account,
        :direction => :outgoing,
        :call_flow => current_call_flow,
        :project => project,
        :address => address,
        :state => :queued,
        :schedule => schedule,
        :not_before => not_before
      )
      call_log.save!
      call_log.info "Received via #{via}: call #{address}"
    end

    if options[:vars].is_a?(Hash)
      variables = {}
      options[:vars].each do |name, value|
        variables[name] = (value =~ /^\d+$/ ? value.to_i : value)
      end
    end

    callback_params = options[:callback_params] if options[:callback_params].is_a?(Hash)

    queued_call = queued_calls.new(
      :call_log => call_log,
      :address => address,
      :callback_url => callback_url,
      :status_callback_url => options[:status_callback_url],
      :flow => flow,
      :not_before => not_before,
      :schedule => schedule,
      :call_flow => current_call_flow,
      :project => project,
      :time_zone => (time_zone ? time_zone.tzinfo.identifier : nil),
      :variables => variables,
      :session_id => session_id,
      :callback_params => callback_params,
    )

    queued_call.not_before = queued_call.schedule.with_time_zone(time_zone) do |time_zoned_schedule|
      time_zoned_schedule.next_available_time(queued_call.not_before || Time.now.utc)
    end if queued_call.schedule

    queued_call.save!

    queued_call
  end

  def has_limit?
    limit.present?
  end

  def broker
    :asterisk_broker
  end

  def call_broker_create_channel
    BrokerClient.create_channel(id, broker) rescue nil
  end

  def call_broker_update_channel
    BrokerClient.create_channel(id, broker) rescue nil
  end

  def call_broker_destroy_channel
    BrokerClient.destroy_channel(id, broker) rescue nil
  end

  def active_calls
    BrokerClient.active_calls_by_channel(id)
  end

  def kind
    self.class.kind
  end

  def self.kind
    self.name.split('::').last
  end

  def self.kinds
    [["#{kind} channel", "#{name}-#{kind}"]]
  end

  def errors_count
    0
  end

  def self.can_handle? a_kind
    subclass_responsibility
  end

  def self.from_json(json)
    channel = (SuitableClassFinder.find_leaf_subclass_of self, suitable_for: json[:kind]).new
    channel.from_json(json)
  end

  def from_json(json)
    self.name = json[:name]
    json_config = json[:config] || {}
    self.class.config_attrs.each do |attr|
      self.send("#{attr}=", json_config[attr])
    end
    self
  end

  def as_json(options = {})
    options = { only: [:name, :config] }.merge(options)
    super(options).merge({
      kind: kind.try(:downcase),
      call_flow: call_flow.try(:name)
    })
  end
end

app/models/channels/custom.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class Channels::Custom < Channel
  config_accessor :dial_string

  def self.can_handle? a_kind
    a_kind == 'custom'
  end
end

app/controllers/api/channels_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api
  class ChannelsController < ApiController

    def get
      channel = current_account.channels.find_by_name params[:name]

      if channel.present?
        render :json => channel
      else
        head :not_found
      end
    end

    def create
      data = request.raw_post
      data = JSON.parse(data).with_indifferent_access
      channel = Channel.from_json data
      channel.account = current_account
      channel.call_flow = current_account.call_flows.find_by_name(data[:call_flow])
      if channel.save
        render :json => channel
      else
        render :json => errors_to_json(channel, 'creating')
      end
    end

    def update
      channel = current_account.channels.find_by_name params[:name]

      if channel.present?
        data = request.raw_post
        data = JSON.parse(data).with_indifferent_access
        channel.from_json data
        if channel.save
          render :json => channel
        else
          render :json => errors_to_json(channel, 'updating')
        end
      else
        head :not_found
      end
    end

    def destroy
      channel = current_account.channels.find_by_name params[:name]

      if channel.present?
        channel.destroy
        head :ok
      else
        head :not_found
      end
    end

    def list
      channel_names = current_account.channels.map(&:name)
      render :json => channel_names
    end

  end
end

app/controllers/channels_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class ChannelsController < ApplicationController
  before_filter :authenticate_account!
  before_filter :load_call_flows, only: [:new, :edit, :create]
  before_filter :load_channel, only: [:show, :edit, :update, :destroy, :call]
  before_filter :check_channel_admin, only: [:update, :destroy]

  # GET /channels
  def index
    @channels = current_account.channels.includes(:call_flow).all
    @shared_channels = current_account.shared_channels.all
    all_channels = @channels + @shared_channels.map(&:channel)

    @channel_kinds = Channel.all_leaf_subclasses.map(&:kinds).flatten(1).sort_by{|x| x[0]}

    grouped_channels = all_channels.each_with_object(Hash.new { |h,k| h[k] = [] }) { |ch, h| h[ch.broker] << ch.id }
    @channel_status = BrokerClient.channel_status(grouped_channels) rescue {}

    @all_channels = @channels.map { |c| [c, nil] } +
                    @shared_channels.map { |sc| [sc.channel, sc.role] }
  end

  # GET /channels/1
  def show
    @errors_count = 0 #@channel.errors_count
    if @channel.project
      @project = current_account.find_project_by_id(@channel.project.id)
    end
  end

  # GET /channels/new
  def new
    if Channel.all_leaf_subclasses.map(&:name).include? params[:type]
      @channel = if params[:type] == 'Channels::TemplateBasedSip'
        params[:type].constantize.send "new_#{params[:template].underscore}_channel"
      else
        params[:type].constantize.new
      end
      @channel.account = current_account
    else
      redirect_to(channels_path, :alert => "Channel type invalid.")
    end
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  def create
    if Channel.all_leaf_subclasses.map(&:name).include? params[:channel][:type]
      @channel = if params[:channel][:type] == 'Channels::TemplateBasedSip'
        params[:channel][:type].constantize.send "new_#{params[:channel][:kind].underscore}_channel"
      else
        params[:channel][:type].constantize.new
      end
      @channel.update_attributes(params[:channel])
      @channel.account = current_account

      if @channel.save
        redirect_to(channels_path, :notice => "Channel #{@channel.name} successfully created.")
      else
        render :action => "new"
      end
    else
      redirect_to(channels_path, :alert => "Channel type invalid.")
    end
  end

  # PUT /channels/1
  def update
    if @channel.update_attributes(params[:channel])
      redirect_to(channels_path, :notice => "Channel #{@channel.name} successfully updated.")
    else
      load_call_flows
      render :action => "edit"
    end
  end

  # DELETE /channels/1
  def destroy
    @channel.destroy

    redirect_to(channels_url)
  end

  def call
    render :layout => false
  end

  private

  def load_call_flows
    t = Project.arel_table
    shared_project_ids = current_account.shared_projects.pluck(:model_id)
    @projects = Project.where(t[:account_id].eq(current_account.id).or(t[:id].in(shared_project_ids))).includes(:call_flows)
  end
end

app/views/channels/_form.haml
= form_for(@channel, :html => {:autocomplete => 'off'}) do |f|
  - if @channel.errors.any?
    #error_explanation
      %h2
        = pluralize(@channel.errors.count, "error")
        prohibited this channel from being saved:
      %ul
        - @channel.errors.full_messages.each do |msg|
          %li= msg
  - readonly = @channel.persisted? && @channel_permission != "admin"
  %a{href: "https://bitbucket.org/instedd/verboice/wiki/ChannelHelp#{@channel.kind}", target: "channel_help_#{@channel.kind.downcase}"}
    .i18b-information
    Help setting up #{@channel.kind.downcase} channels
  %br
  %br
  .field
    = f.label :name
    = f.text_field :name, readonly: readonly
  .field
    = f.label :call_flow_id, "Call flow for incoming calls"
    = f.select :call_flow_id, option_groups_from_collection_for_select(@projects, :call_flows, :name, :id, :name, @channel.call_flow_id), {:include_blank => 'None'}, {disabled: readonly}
  = f.hidden_field :type
  = render "form_#{@channel.class.name.split('::').last.underscore}", :f => f, :readonly => readonly
  - if @channel.new_record? || channel_admin?
    .actions
      %hr
        - if @channel.new_record?
          %button.white{:type => "submit"} Save
        - else
          %button.white{:type => "submit"} Update
        = link_to 'Cancel', @channel, :class => "button white cancel #{@channel.new_record? ? 'remove_unsaved_element' : 'collapse_trigger'}", :style => 'top: 1px;'

app/views/channels/_form_custom.haml
.field
  = f.label :dial_string
  = f.text_field :dial_string, readonly: readonly
.field
  = f.label :limit
  = f.text_field :limit, readonly: readonly

app/views/channels/_form_custom_sip.haml
.field
  = f.label :username
  = f.text_field :username, :autocomplete => 'off', readonly: readonly
.field
  = f.label :password
  = f.password_field :password, :value => @channel.password, :autocomplete => 'off', readonly: readonly
.field
  = f.label :number
  = f.text_field :number, readonly: readonly
.field
  = f.label :limit
  = f.text_field :limit, readonly: readonly
.field
  = f.label :domain
  = f.text_field :domain, readonly: readonly
.field
  = f.label :direction
  = f.select :direction, [['Incoming', 'inbound'], ['Outgoing', 'outbound'], ['Both directions', 'both']], {}, {disabled: readonly}
.field
  = f.label :register, style: 'display:inline-block'
  = f.check_box :register

app/views/channels/_form_template_based_sip.html.haml
.field
  = f.label :username
  = f.text_field :username, :autocomplete => 'off', readonly: readonly
.field
  = f.label :password
  = f.password_field :password, :value => @channel.config['password'], :autocomplete => 'off', readonly: readonly
.field
  = f.label :number
  = f.text_field :number, readonly: readonly
.field
  = f.label :limit
  = f.text_field :limit, readonly: readonly

  = f.hidden_field :kind

app/views/channels/_form_twilio.haml
.field
  = f.label :account_sid
  = f.text_field :account_sid, readonly: readonly
.field
  = f.label :auth_token
  = f.text_field :auth_token, readonly: readonly
.field
  = f.label :number
  = f.text_field :number, readonly: readonly
.field
  = f.label :limit
  = f.text_field :limit, readonly: readonly

app/views/channels/_form_voxeo.haml
.field
  = f.label :token
  = f.text_field :token, readonly: readonly
.field
  = f.label :url
  = f.text_field :url, readonly: readonly
.field
  = f.label :limit
  = f.text_field :limit, readonly: readonly

app/views/channels/_show_voxeo.haml
- config = Rails.configuration.voxeo_configuration[:http_url_options]
%p
  Use this URL as the "Voice URL" in your Voxeo settings:
  %br
  = "http://#{config[:host]}:#{config[:port]}/?channel_guid=#{channel.guid}"

app/views/channels/call.html.erb
<div id="call_progress">
  <p>Call channel <%= @channel.name %>.</p>

  <form onsubmit="call_channel(); return false">
    Number: <input type="text" name="number" id="number" />

    <input type="submit" value="Call">
  </form>

  <script type="text/javascript">
  window.call_id = null;
  window.call_finished = false;

  function call_channel() {
    var path = '<%= api_call_path :channel => @channel.name %>&address=' + $('#number').val();
    $.get(path, '', function(data) {
      window.call_id = data.call_id;
      setInterval(refresh_call_progress, 1000);
      refresh_call_progress();
    });
  }

  function refresh_call_progress() {
    if (window.call_finished) return;

    $('#call_progress').load('/calls/' + window.call_id + '/progress');
  }
  </script>
</div>

app/views/channels/edit.haml
= render 'shared/channel_tabs_and_title', :channel => @channel, :shared_channel => @shared_channel

%h1 Settings

= render 'form'

app/views/channels/index.haml
%h2 Channels
= render partial: '/shared/channels_tabs'

%br
.tablewrapp.w60
  %table.GralTable.TwoColumn.CleanTable.ItemsTable{:class => ('empty' if @channels.empty?)}
    %tr
      %th My Channels
      %th
        = select_tag('new_channel', options_for_select(@channel_kinds), onchange: 'create_channel(this)', prompt: 'Create new...')
    - if @all_channels.empty?
      %tr
        %td.EmptyFolder{:colspan => 100}
          %br
          You have no voice channels yet.
          %br
          = select_tag('new_channel', options_for_select(@channel_kinds), onchange: 'create_channel(this)', prompt: 'Create new...')
    - else
      - @all_channels.each do |channel, permission|
        %tr.link{'data-url' => channel_path(channel)}
          %td
            - status = @channel_status[channel.id]
            - status_ok = status.nil? || status[:ok]
            %span{style: "display: inline-block; width: 10px; height: 10px; background-color: #{ status ? (status_ok ? '#6BD346' : '#FF642A') : '#D0D0D0' }"}
            = channel.name
            - if permission
              (shared as #{permission})
            - unless status_ok
              %br
              - status[:messages].each do |message|
                %label.error
                  = message
                %br
          %td
            %button.farrow{:type => :button}
    %tr

app/views/channels/new.html.erb
<h2>New <%= @channel.kind %> channel</h2>

<%= render 'form' %>

app/views/channels/show.haml
= render 'shared/channel_tabs_and_title', :channel => @channel, :shared_channel => @shared_channel

%h1 Calls
%p Total number of calls made and received

.sbox.grey.StateDisplay.w30
  .values
    .U
      %span.big= @channel.call_logs.size
      %span= "#{@channel.call_logs.size == 1 ? 'call' : 'calls'} registered"
  = link_to 'Download as CSV', download_call_logs_path(:format => :csv, :search => "channel_id:\"#{@channel.id}\""), :class => "button white"

%br/
%hr/
%br/

%h1 Properties

%ul.call-properties.left
  %li
    .i48grad-call-flow
    %div{style: 'overflow: hidden'}
      %span
        %nobr Default Call flow
        - if @channel.call_flow
          %nobr= @channel.call_flow.name
        - else
          None
    - if @project
      = link_to "Manage Call Flow", project_call_flows_path(@project), :class => "button farrow"
  %li
    .i48grad-time
    %div
      %span= pluralize @channel.queued_calls.size, 'queued call'
    = link_to "View calls", queued_call_logs_path, :class => "button farrow"
  - if @channel.is_a?(Channels::Sip)
    %li
      .i48grad-dataBase
      %div
        - if @errors_count == 0
          %span No errors
        - else
          %span.orange #{pluralize @errors_count, 'error'}
      = link_to "Edit settings", edit_channel_path(@channel), :class => "button farrow"

%br{ :clear => 'left'}

%hr

- if channel_admin?
  = link_to 'Delete this channel', @channel, :confirm => "Are you sure you want to delete the channel #{@channel.name}?", :method => :delete, :class => "button fdelete"
.clear