config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

Verboice::Application.routes.draw do

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :account

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show]

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      get :download
    end
  end

  resource :synthesizer do
    get :voices
  end

  resources :alerts do
    member do
      get :dismiss
    end
  end

  namespace :api do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end
    end
    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end
  end

  get 'permissions' => 'permissions#index'
  get 'permissions/autocomplete' => 'permissions#autocomplete'
  post 'permissions/add_account' => 'permissions#add_account'
  post 'permissions/update' => 'permissions#update'

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/models/call_log.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class CallLog < ActiveRecord::Base
  include CallLogSearch

  belongs_to :account
  belongs_to :project
  belongs_to :call_flow
  belongs_to :channel
  belongs_to :schedule
  has_many :traces, :foreign_key => 'call_id'
  has_many :entries, :foreign_key => 'call_id', :class_name => "CallLogEntry"
  has_many :pbx_logs, :foreign_key => :guid, :primary_key => :pbx_logs_guid

  before_validation :set_account_to_project_account, :if => :call_flow_id?

  validates_presence_of :account
  validates_presence_of :project
  validates_presence_of :channel

  def state
    read_attribute(:state).try(:to_sym)
  end

  def direction
    read_attribute(:direction).try(:to_sym)
  end

  def outgoing?
    direction == :outgoing
  end

  def incoming?
    direction == :incoming
  end

  def start_incoming
    info "Answering call from #{address}"
    start
  end

  def start_outgoing(address)
    self.address = address
    info "Calling #{address}"
    start
  end

  def start
    self.state = :active
    self.started_at = Time.now.utc
    self.save!
  end

  def finish_with_error(message)
    self.fail_reason = message
    finish :failed
  end

  def finish_successfully
    self.fail_reason = ''
    finish :completed
  end

  def finish(state)
    self.state = state
    self.finished_at = Time.now.utc
    self.save!

    begin
      call_flow.try(:push_results, self) if call_flow && call_flow.store_in_fusion_tables
    rescue Exception => ex
      logger.error "Error pushing call flow results #{ex.message}\n#{ex.backtrace.join("\n")}"
    end
  end

  def structured_details
    entries.inject [] do |logs, call_log_entry|
      logs << {:severity => call_log_entry.severity, :time => call_log_entry.created_at, :text => call_log_entry.description}
    end
  end

  CallLogEntry::Levels.each do | severity |
    class_eval <<-EVAL, __FILE__, __LINE__ + 1
      def #{severity}(description, options = {})
        log :#{severity}, description, options
      end
    EVAL
  end

  def log(level, description, options = {})
    CallLogEntry.create!(
      severity: level,
      description: description,
      call_id: self.id,
      step_id: options[:step_id],
      step_name: options[:step_name],
      command: options[:command],
      action: options[:action]
    )
  end

  def last_entry
    self.entries.order('created_at DESC, id DESC').first
  end

  def self.poirot_activities(id_or_ids)
    if Rails.configuration.verboice_configuration[:poirot_elasticsearch_url]
      Hercule::Activity.search({size: 1000000, filter: {
        and: [
          { term: { call_log_id: id_or_ids } },
          { exists: { field: "step_type" } }
        ]
      }}).items
    else
      entries = CallLogEntry.where(call_id: id_or_ids)
      activities = entries.select { |x| x.details.has_key?(:activity) }.map do |x|
        activity = JSON.load(x.details[:activity])
        Hercule::Activity.new({'_source' => activity["body"]})
      end
    end
  end

  private

  def set_account_to_project_account
    self.project_id = self.call_flow.project_id
    self.account_id = self.project.account_id
  end
end

app/controllers/call_logs_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class CallLogsController < ApplicationController
  before_filter :authenticate_account!

  def index
    @page = params[:page] || 1
    @search = params[:search]
    @per_page = 10
    @logs = current_account.call_logs.includes(:project).includes(:channel).order('id DESC')
    @logs = @logs.search @search, :account => current_account if @search.present?
    @logs = @logs.paginate :page => @page, :per_page => @per_page
  end

  def show
    set_fixed_width_content
    @log = current_account.call_logs.find params[:id]
    @activities = CallLog.poirot_activities(@log.id).sort_by(&:start)
  end

  def progress
    @log = current_account.call_logs.find params[:id]
    render :layout => false
  end

  def queued
    @page = params[:page] || 1
    @per_page = 10
    @calls = current_account.queued_calls.includes(:channel).includes(:call_log).includes(:schedule).order('id DESC')
    @calls = @calls.paginate :page => @page, :per_page => @per_page
  end

  def play_result
    @log = current_account.call_logs.find params[:id]
    send_file RecordingManager.for(@log).result_path_for(params[:key]), :x_sendfile => true
  end

  def download
    @filename = "Call_logs_(#{Time.now.to_s.gsub(' ', '_')}).csv"
    @streaming = true
    @csv_options = { :col_sep => ',' }
  end

  def download_details
    @log = current_account.call_logs.includes(:entries).find params[:id]
    @filename = "Call details #{@log.id} (#{Time.now}).csv"
    @streaming = true
    @csv_options = { :col_sep => ',' }
  end

end

app/views/call_logs/_tabs.haml
%ul.tabs.top
  %li{ :class =>"#{"active" if params[:controller] == "call_logs" && (params[:action] == 'show' || params[:action] == 'index' || params[:action] == 'progress')}"}
    = link_to "Calls log", call_logs_path
  %li{ :class =>"#{"active" if params[:controller] == "call_logs" && (params[:action] == 'queued' || params[:action] == 'enqueue')}"}
    = link_to "Queued calls", queued_call_logs_path
.tabsline

app/views/call_logs/index.haml
= render :partial => 'call_logs/tabs'

%p
  Here you can see the details of incoming and outgoing calls.
%form
  %p
    Search: #{text_field_tag :search, @search, :size => 80, :class => (@search.present? ? 'highlighted' : '')}
  %p
    = link_to 'Download as CSV', download_call_logs_path(:format => :csv, :search => @search), :class => "button fimport"
  %div= page_entries_info @logs, :entry_name => 'call log'
  - if @logs.present?
    %br/
    %table.GralTable
      %tr
        %th ID
        %th Started
        %th Finished
        %th Duration
        %th Caller ID
        %th Direction
        %th Channel
        %th Queue
        %th Project
        %th Call Flow
        %th State
        %th
      - @logs.each do |log|
        %tr
          %td= log.id
          %td= raw time_ago log.created_at
          %td= raw time_ago log.finished_at
          %td= distance_of_time_in_words(log.finished_at, log.created_at, true) if log.finished_at
          - if log.address.present?
            %td= link_to log.address, call_logs_path(:search => "caller:#{log.address}")
          - else
            %td= log.address
          %td= log.direction
          %td= log.channel.try(:name)
          %td= log.schedule.try(:name)
          %td= log.project.try(:name)
          %td= log.call_flow.try(:name)
          %td
            = log.state
            - if log.fail_reason.present?
              = "(#{log.fail_reason})"
          %td= link_to 'view details', call_log_path(log)
    %br/

%div#call_logs_paginator
  = form_tag({action: :index, controller: :call_logs}, method: :get) do
    - total_pages = (@logs.count/@per_page)+1

    - previous_btn_class = 'pprevious' + (if (@page.to_i - 1) < 1 then " disabled" else '' end)
    = link_to '', {action: 'index', page: @page.to_i-1}, class: previous_btn_class

    - next_btn_class = 'pnext' + (if (@page.to_i + 1) > total_pages then " disabled" else '' end)
    = link_to '', {action: 'index', page: @page.to_i+1}, class: next_btn_class

    = text_field_tag 'page', @page.to_i
    %span.label-info="of #{total_pages}"
    = submit_tag '', class: 'hidden'

%br/

app/views/call_logs/progress.html.erb
<p>Call with <%= @log.address %> from channel <%= @log.channel.name %> (<%= @log.state %>)</p>
<br />

<table class="GralTable">
  <tr>
    <th>Severity</th>
    <th>When</th>
    <th>Text</th>
  </tr>
  <% @log.structured_details.reverse.each do |detail| %>
    <tr class="<%= detail[:severity] %>">
      <td><%= detail[:severity] %></td>
      <td><%= detail[:time] %></td>
      <td><%= short_html detail[:text], 40 %></td>
    </tr>
  <% end %>
</table>

<% if @log.state == :completed || @log.state == :failed %>
  <script type="text/javascript">
    window.call_finished = true;
  </script>
<% end %>

app/views/call_logs/queued.haml
= render 'tabs'

%h2 Queued calls
%p
  Here you can see the details of enqueued calls.
%form
  %div= page_entries_info @calls, :entry_name => 'queued calls'
  = will_paginate @calls, :param_name => 'page'
  - if @calls.present?
    %br/
    %table.GralTable
      %tr
        %th ID
        %th Channel
        %th Date
        %th Phone number
        %th Queue
        %th Project
        %th State
        %th
      - @calls.each do |call|
        %tr
          %td= call.id
          %td= call.channel.try(:name)
          %td= call.not_before
          %td= call.address
          %td= call.schedule.try(:name)
          %td= call.project.try(:name)
          %td= call.call_log.try(:state)
          %td
            = link_to 'view log details', call_log_path(call.call_log)
            = link_to '', [call.channel, call], :confirm => "Are you sure you want to delete the call #{call.address}?", :method => :delete, :class => "button fdelete"
    %br/
    %div= page_entries_info @calls, :entry_name => 'queued calls'
    = will_paginate @calls, :param_name => 'page'

app/views/call_logs/show.haml
%h2 Call log ##{@log.id}
.call-log-header
  .item
    %b Not Before:
    = @log.not_before
  .item
    %b Started:
    = format_timestamp(@log.created_at)
  .item
    %b Finished:
    = format_timestamp(@log.finished_at)
  .item
    %b Duration:
    = distance_of_time_in_words(@log.finished_at, @log.created_at, true) if @log.finished_at
  .item
    %b Phone number:
    = @log.address
  .item
    %b Direction:
    = @log.direction
  .item
    %b Channel:
    = @log.channel.try(:name)
  .item
    %b Schedule:
    = @log.schedule.try(:name)
  .item
    %b Project:
    = @log.project.try(:name)
  .item
    %b State:
    = @log.state
  .item
    %b Fail Reason:
    = @log.fail_reason
%br/
%p
  = link_to 'Download CSV', download_details_call_log_path(@log, :format => :csv), :class => "button fimport"

.tablewrapp.user-flow-log
  %table
    -@activities.each do |activity|
      %tr{:class => activity.fields['error'] ? 'error' : ''}
        %td.timestamp
          - time = Time.parse(activity.start)
          = l(time.to_date, format: :short)
          %br
          = time.strftime("%H:%M:%S.%L")
        %td.icon
          %div{:class => user_step_class(activity.fields['step_type'], !!activity.fields['error'])}
        %td.details
          .step_name= activity.description
          .description
            = activity.fields['error']
            = activity.fields['step_result']
            = activity.fields['step_data']

- if @log.pbx_logs_guid
  %h3 Network Logs
  %table.GralTable
    %tr
      %th{style: 'width:160px;'} When
      %th Details
    - @log.pbx_logs.each do |pbx_log|
      %tr
        %td= pbx_log.created_at
        %td= pbx_log.details
  %br