config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

Verboice::Application.routes.draw do

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  guisso_for :account

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show]

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      get :download
    end
  end

  resource :synthesizer do
    get :voices
  end

  resources :alerts do
    member do
      get :dismiss
    end
  end

  namespace :api do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end
    end
    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end
  end

  get 'permissions' => 'permissions#index'
  get 'permissions/autocomplete' => 'permissions#autocomplete'
  post 'permissions/add_account' => 'permissions#add_account'
  post 'permissions/update' => 'permissions#update'

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/models/project.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class Project < ActiveRecord::Base

  serialize :languages

  belongs_to :account
  belongs_to :default_call_flow, :class_name => "CallFlow", :foreign_key => "call_flow_id"

  has_many :call_flows, :dependent => :destroy
  has_many :call_logs, :dependent => :nullify
  has_many :queued_calls, :dependent => :destroy
  has_many :external_services, :dependent => :destroy
  has_many :external_service_steps, :through => :external_services
  has_many :schedules, :dependent => :destroy
  has_many :contacts, :dependent => :destroy
  has_many :contact_addresses
  has_many :persisted_variables, :through => :contacts
  has_many :project_variables, :dependent => :destroy, :inverse_of => :project
  has_many :resources, :dependent => :destroy
  has_many :localized_resources, through: :resources
  has_many :feeds
  has_many :recorded_audios
  has_many :project_permissions, :foreign_key => "model_id", :dependent => :destroy

  accepts_nested_attributes_for :project_variables,
    :reject_if => lambda { |attributes| attributes[:name].blank?},
    :allow_destroy => true

  attr_accessible :name, :account, :status_callback_url, :status_callback_url_user, :status_callback_url_password, :time_zone, :project_variables_attributes, :languages, :default_language
  attr_accessible :tts_engine, :tts_ispeech_api_key

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :account_id

  config_accessor :status_callback_url_user, :status_callback_url_password
  config_accessor :tts_engine, :tts_ispeech_api_key

  attr_encrypted :config, :key => ENCRYPTION_KEY, :marshal => true

  before_validation :sanitize_languages

  validates_presence_of :tts_ispeech_api_key, :if => ->{ tts_engine == 'ispeech' }

  broker_cached

  def defined_variables
    project_variables.collect(&:name)
  end

  def update_variables_with variable_names
    variable_names.each do |variable_name|
      unless project_variables.any? {|var| var.name == variable_name}
        project_variables.create! name: variable_name
      end
    end
  end

  def default_language
    self['default_language'] || 'en'
  end

  def languages
    self['languages'] || [{'language' => 'en'}]
  end

  def synthesizer
    @synthesizer ||= begin
      if tts_engine == 'ispeech'
        TTS::ISpeechSynthesizer.new(api_key: tts_ispeech_api_key)
      else
        TTS::SystemSynthesizer.instance
      end
    end
  end

  def active_calls
    BrokerClient.active_calls_by_project(id)
  end

  private

  def sanitize_languages
    self.languages = Set.new(languages.reject{|l| l.blank?}).to_a
  end

end

app/controllers/api/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api
  class ProjectsController < ApiController
    def index
      projects = current_account.projects.includes(:call_flows, :schedules).sort_by { |p| p.name.downcase }.map do |project|
        {
          id: project.id,
          name: project.name,
          call_flows: project.call_flows.sort_by { |c| c.name.downcase }.map do |call_flow|
            {
              id: call_flow.id,
              name: call_flow.name,
            }
          end,
          schedules: project.schedules.map(&:name).sort_by { |n| n.downcase },
        }
      end
      render json: projects
    end
  end
end

app/controllers/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class ProjectsController < ApplicationController
  before_filter :authenticate_account!
  before_filter :load_project, only: [:edit, :update, :update_variables]
  before_filter :load_enqueue_call_fields, only: [:show, :enqueue_call]
  before_filter :check_project_admin, only: [:update, :update_variables]

  def index
    @projects = current_account.projects.all
    @shared_projects = current_account.shared_projects.all
    @all_projects = @projects.map { |p| [p, nil] } +
                    @shared_projects.map { |sp| [sp.project, sp.role] }
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
    @project.account = current_account

    if @project.save
      redirect_to(project_call_flows_path(@project), :notice => "Project #{@project.name} successfully created.")
    else
      render :action => "new"
    end
  end

  def update
    if @project.update_attributes(params[:project])
      redirect_to(project_path(@project), :notice => "Project #{@project.name} successfully updated.")
    else
      render :action => "edit"
    end
  end

  def enqueue_call
    redirect_to project_path(params[:id]), flash: {error: 'You need to select a Call Flow'} and return unless params[:call_flow_id].present?

    @channel = @channels.find { |c| c.id == params[:channel_id].to_i }
    redirect_to project_path(params[:id]), flash: {error: 'You need to select a channel'} and return unless @channel

    addresses = params[:addresses].split(/\n/).map(&:strip).select(&:presence)

    options = {}
    options[:account] = current_account
    options[:schedule_id] = params[:schedule_id] if params[:schedule_id].present?
    options[:not_before] = "#{params[:not_before_date]} #{params[:not_before_time]}" if params[:not_before_date].present? && params[:not_before].present?
    options[:time_zone] = params[:time_zone] if params[:time_zone].present?
    options[:call_flow_id] = params[:call_flow_id] if params[:call_flow_id].present?
    options[:project_id] = params[:id]
    options[:vars] = params[:vars]

    DateTime.parse(options[:not_before]) rescue redirect_to project_path(params[:id]), flash: {error: 'Enter a valid date'} and return if options[:not_before]

    addresses = curated_addresses(addresses)
    addresses.each do |address|
      @channel.call(address.strip, options)
    end

    redirect_to project_path(params[:id]), {:notice => "Enqueued calls to #{pluralize(addresses.count, 'address')} on channel #{@channel.name}"}
  end

  def destroy
    @project = current_account.projects.find(params[:id])
    @project.destroy
    redirect_to(projects_url, :notice => "Project #{@project.name} successfully deleted.")
  end

  def update_variables
    if @project.update_attributes(params[:project])
      redirect_to project_contacts_path(@project), notice: "Columns successfully updated."
    else
      redirect_to project_contacts_path(@project), flash: { error: "Error updating columns."}
    end
  end

  private

  def load_enqueue_call_fields
    load_project
    @channels = current_account.channels.all

    shared_channels = current_account.shared_channels.all.map(&:channel)
    shared_channels.each { |c| c.name = "#{c.name} (shared)" }
    @channels.concat shared_channels

    @schedules = @project.schedules
    @call_flows = @project.call_flows.includes(:channels).includes(:queued_calls)
    @project_channels = @call_flows.collect(&:channels).flatten.to_set
    @queued_calls = @call_flows.collect(&:queued_calls).flatten
    @call_logs = @project.call_logs
  end

  def curated_addresses(addresses)
    # build a hash from contact_id to all his addresses
    # eg. { 1 => ['123','456'], 2 => ['789'] }
    all_contacts = Hash.new { |hash,key| hash[key] = [] }
    all_contacts = @project.contact_addresses.order(:id).inject(all_contacts) do |contacts, contact_address|
      contacts[contact_address.contact_id] << contact_address.address
      contacts
    end
    # now build a hash from every contact's addresses to all his addresses
    # eg. { '123' => ['123', '456'], '456' => ['123', '456'], '789' => ['789'] }
    all_addresses = all_contacts.values.inject({}) do |all_addresses, contact_addresses|
      contact_addresses.each do |contact_address|
        all_addresses[contact_address] = contact_addresses
      end
      all_addresses
    end

    # curate the addresses so that there is only one entry for each contact in
    # the original list, and that entry is the contact's first registered address
    known_addresses = Set.new
    addresses.inject([]) do |curated, address|
      unless known_addresses.include?(address)
        contact_addresses = all_addresses[address]
        if contact_addresses.nil?
          known_addresses << address
          curated << address
        else
          known_addresses.merge(contact_addresses)
          curated << contact_addresses.first
        end
      end
      curated
    end
  end
end

app/helpers/project_helper.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

module ProjectHelper

  def project_languages_json(project)
    project.languages.map { |lang| {key: lang['language'], value: LanguageList::LanguageInfo.find(lang['language']).name} }.to_json
  end

end

app/views/projects/_enqueue_new_call.html.haml
.box.w30.right.lmargin.enqueue_new_call
  %h2 Enqueue new calls
  %p.desc Add new calls to this project queue
  = form_tag enqueue_call_project_path, :method => 'POST' do
    %p
      = label_tag :call_flow_id, 'Call Flow'
      %br/
      = select_tag :call_flow_id, options_from_collection_for_select(call_flows, 'id', 'name'), :prompt => 'Select a Call Flow...', :class => 'w30'
    %p
      = label_tag :channel_id, 'Channel'
      %br/
      = select_tag :channel_id, options_from_collection_for_select(channels, 'id', 'name'), :prompt => 'Select a Channel...', :class => 'w30'
    %p
      = label_tag :schedule_id, 'Schedule'
      %br/
      = select_tag :schedule_id, options_from_collection_for_select(schedules, 'id', 'name'), :prompt => 'Select a Schedule...', :class => 'w30'
    %p
      = check_box_tag :not_before
      = label_tag :not_before, 'Not before'
      %br/
      = text_field_tag :not_before_date, '', :class => "ux-custom-datepicker ux-datepicker w10"
      = text_field_tag :not_before_time, '00:00', :class => 'w10', :alt => 'time'
    %p
      = label_tag :time_zone, 'On time zone'
      %br/
      = select_tag :time_zone, time_zone_options_for_select(project.time_zone, TZInfo::Timezone.all.sort, TZInfo::Timezone), :class => 'w30'
    %p
      = label_tag :language
      %br/
      = select_tag :language, options_for_select(project.languages.map { |lang| [LanguageList::LanguageInfo.find(lang['language']).name, lang['language']] }), prompt: 'None specified', name: 'vars[language]'
    - if project.project_variables.any?
      %p
        .ux-collapsible.collapsed
          %span
            %a.arrow{href: "#"}
              = label_tag :variables
          .ux-content
            - project.project_variables.each do |var|
              %br/
              = label_tag var.name, var.name.downcase
              %br/
              = text_field_tag var.name, '', name: "vars[#{var.name}]"
            - project.external_services.each do |service|
              - service.global_variables.each do |var|
                %br/
                = label_tag var.name, var.display_name
                %br/
                = text_field_tag var.name, '', name: "vars[#{var.name}]"
    %p
      = label_tag :addresses, 'Phone numbers'
      %br/
      %span.desc Enter each phone number in a separate line
      %p
        = text_area_tag :addresses, nil, :placeholder => "555-1000", :rows => 10, :class => 'w30'
    %p
      = button_tag "Enqueue calls", :class => 'orange'

app/views/projects/_form.haml
- content_for :head do
  :javascript
    $(function() { initProjectSettings(#{@project.default_language.to_json}, #{@project.languages.to_json}, #{@project.synthesizer.voices.to_json}); });

- readonly = @project.persisted? && @project_permission != "admin"

= form_for(@project, :builder => InsteddFormBuilder) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  %br

  %h1 Properties

  = f.text_field :name, readonly: readonly
  = f.time_zone_select(:time_zone, TZInfo::Timezone.all.sort, {:model => TZInfo::Timezone}, {disabled: readonly})

  %hr

  %br
  %br

  %h1 Languages

  = f.label :default_language
  %br
  %select.w30{ko(value: 'defaultLanguage', options: 'languages', optionsText: "'label'", optionsValue: "'value'"), name: 'project[default_language]', disabled: readonly}

  %br
  %br
  = f.select(:tts_engine, options_for_select([['Built in', 'built-in'], ['iSpeech', 'ispeech']], @project.tts_engine), {label: 'Text-to-speech Engine'}, {disabled: readonly})
  = f.text_field :tts_ispeech_api_key, label: 'iSpeech API key'

  = f.label :languages, "Languages you will support in this project"
  %br

  %ul.clist.w30
    /ko foreach: languages
    %li
      %input{ko(value: 'value'), type: 'hidden', name: 'project[languages][][language]'}
      %span.w15{ko(text: 'description')}
      %select.w15{ko(value: 'voice', options: 'voices()', optionsText: "'description'", optionsValue: "'id'"), name: 'project[languages][][voice]', disabled: readonly}
      - unless readonly
        %button.clist-remove{ko(click: '$root.removeLanguage')}
    //ko
    - unless readonly
      %li
        %input#add_language.ux-type{ko(value: 'newLanguage', valueUpdate: 'afterkeydown', event: {keydown: 'keydown'}), type: 'text', placeholder: 'Add a new language'}
        %button#add_language_button.clist-add{ko(click: 'addLanguage')}

  %br

  %hr

  %br
  %br

  %h1 Status callback

  = f.text_field :status_callback_url, :label => 'URL', readonly: readonly
  = f.text_field :status_callback_url_user, :label => 'User', :autocomplete => 'off', readonly: readonly
  = f.password_field :status_callback_url_password, :label => 'Password', :autocomplete => 'off', readonly: readonly

  - if @project.new_record? || project_admin?
    %hr
      - if @project.new_record?
        %button.grey{:type => "submit"} Save
        = link_to "Cancel", projects_path, :class => "button white cancel", :style => 'top: 1px;'
      - else
        %button.grey{:type => "submit"} Update
        = link_to "Cancel", project_path(@project), :class => "button white cancel", :style => 'top: 1px;'

app/views/projects/edit.haml
= render 'shared/project_tabs_and_title', :project => @project, :shared_project => @shared_project

= render 'form'

app/views/projects/index.haml
%h2 Projects

%br
.tablewrapp.w60
  %table.GralTable.TwoColumn.CleanTable.ItemsTable{:class => ('empty' if @projects.empty?)}
    %tr
      %th My Projects
      %th
    - if @all_projects.empty?
      %tr
        %td.EmptyFolder{:colspan => 100}
          %br
          You have no projects yet.
          %br
          = link_button_to ('Create Project'), new_project_path, :class => 'EmptyAddButton button cadd'
    - else
      - @all_projects.each do |project, permission|
        %tr.link{'data-url' => project_path(project)}
          %td
            = project.name
            - if permission
              (shared as #{permission})
          %td
            %button.farrow{:type => :button}
      %tr.link{'data-url' => new_project_path}
        %td Create Project
        %td
          %button.cadd

app/views/projects/new.haml
%h2 New project
= render 'form'

app/views/projects/show.haml
= render 'shared/project_tabs_and_title', :project => @project, :shared_project => @shared_project

= render 'enqueue_new_call', :project => @project, :call_flows => @call_flows, :channels => @channels, :schedules => @schedules

%h1 Calls
%p Total number of calls made and received

.sbox.grey.StateDisplay.w30
  .values
    .U
      %span.big= @call_logs.size
      %span= "#{@call_logs.size == 1 ? 'call' : 'calls'} registered"
  = link_to 'Download as CSV', download_call_logs_path(:format => :csv, :search => "project_id:\"#{@project.id}\""), :class => "button white"

%br/
%hr/
%br/

%h1 Properties

%ul.call-properties.left
  %li
    .i48grad-call-flow
    %div
      %span="#{pluralize @call_flows.size, 'Call flow'} in this project"
    = link_to "Edit Call Flows", project_call_flows_path(@project), :class => "button farrow"
  %li
    .i48grad-channel
    %div
      %span= "#{pluralize @project_channels.size, 'channel'} in this project"
    = link_to "Manage channels", channels_path, :class => "button farrow"

  %li
    .i48grad-time
    %div
      %span= pluralize @queued_calls.size, 'queued call'
    = link_to "View calls", queued_call_logs_path, :class => "button farrow"

%br{ :clear => 'left'}

= link_to 'Edit settings', edit_project_path(@project), :class => "button farrow"
%hr

- if project_owner?
  = link_to 'Delete this project', @project, :confirm => "Are you sure you want to delete the project #{@project.name}?", :method => :delete, :class => "button fdelete"
.clear